[phases.setup]
nixPkgs = ["php82", "nodejs_20"]

[phases.install]
cmds = [
  "curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer"
]

[phases.build]
cmds = [
  "composer install --optimize-autoloader --no-dev --no-interaction",
  "npm install",
  "npm run build"
]
